# Generated by Django 5.2.5 on 2026-03-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
