# Generated by Django 5.2.5 on 2026-03-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_student_payment_date_student_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
