# Generated by Django 5.2.5 on 2026-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_student_payment_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='subjective_answer',
            new_name='answer_text',
        ),
        migrations.AddField(
            model_name='response',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='selected_option',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
