# Generated by Django 5.2.5 on 2026-04-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_rename_subjective_answer_response_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(default='student', max_length=10),
        ),
    ]
